### ISSUE TITLE
Reference to "dead change" attack

### ISSUE THREAD

**Issue by kristovatlas** [nopara73/ZeroLink#24]
> If the post-mix wallet would function as a normal Bitcoin wallet too, the observer would notice post-mix transactions. Those are joining together mixed outputs. Since pre-mix wallets naturally divide and join utxos in order to fund a mixing round with the correct amount, similarly to CoinJoin Sudoku, a simple amount analysis on transactions chains, instead of transactions could re-establish links between pre-mix and post-mix wallets.

On a related note: A Dash community member back in 2014 named "Aswan" first observed the problem with spending coins that have been CoinJoined, which is that the resulting change is now tainted by the context of the spend and needs to be CoinJoined again. He called this a "dead change" attack. You may find it helpful to refer to this for historical purposes. https://www.dash.org/forum/threads/dead-change-an-anonymity-issue.3019/

I can submit a PR for this if it sounds valuable.

**Comment by nopara73** [comment]
Yes, it is valuable. I spent quite some time of thinking about it and I succeeded to make some incremental improvement with much implementation overhead and useability degradation.  

To enhance useability of a post-mix wallet
- the wallet MAY implement coin control feature, 
- the wallet MAY offer the user to donate smaller change outputs, instead of getting them back. This could even finance the development of such wallet,  
- the wallet MAY also implement a visualized transaction history, instead of a traditional wallet history.

##### Dead Change Attack

![](http://i.imgur.com/3LtkqNA.png)

While the recommended strict coin selection properly separates mixed coins from each other, it does not protect against the [dead change attack](https://www.dash.org/forum/threads/dead-change-an-anonymity-issue.3019/). Change outputs will be used for different purposes, therefore it is possible to connect those payments together. Fortunately it does not affect the anonymity set of other users who participated in the mix, but it does affect individual privacy.  
To encourage more cautious user behavior post-mix wallet MAY implement a transaction labeling system, so users can decide manually what purcheses it does not care about if they are connected together by third party observers.  

Furthermore it is possible to completely defeat the dead change attack for the first transaction after the mix, the post-mix wallets MAY make the users' first purchase to be a regular CoinJoin transaction, without the usage of fixed denomination. In this CoinJoin every input transaction is the same denomination, therefore an observer will not be able to tell who wanted to pay who and it cannot come to conclusions about the changes either.  
In this case the Chaumian CoinJoin technique must be modified in a way that the active CoinJoin output must be provided in a separate phase, otherwise the change attack defense would not work against the Tumbler.

![](http://i.imgur.com/kyqH9wy.png)

**Comment by nopara73** [comment]
If you have no other idea in your mind I think the issue can be closed.

**Comment by nopara73** [comment]
I was wrong about my dead change attack defense idea, it does not help in any way against dead change. However the method adds more anonymity set. The modified section:

##### Additional Anonymity Set

A post-mix wallet MAY offer to make a user's first purchase to be a regular CoinJoin transaction, without the usage of fixed denomination so additional anonymity set can be achieved. In this CoinJoin every input transaction is the same denomination, therefore an observer will not be able to tell who wanted to pay who, it can only figure out which change belongs to which active output.  

![](https://i.imgur.com/1IotuiI.png)
